repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-added-large-files
        args: ['--maxkb=1024']
    -   id: check-shebang-scripts-are-executable
    -   id: check-executables-have-shebangs
