#define CONFIG_LUNAIX_VER "dev-2024_477612"
// #define CONFIG_NO_ASSERT
#define CONFIG_ARCH_I386 
// #define CONFIG_X86_ENABLE_SSE_FEATURE
#define CONFIG_X86_BOOT_OPTIONS_MULTIBOOT 
#define CONFIG_PMALLOC_METHOD_SIMPLE 
#define CONFIG_PMALLOC_SIMPLE_MAX_PO0 4096
#define CONFIG_PMALLOC_SIMPLE_MAX_PO1 2048
#define CONFIG_PMALLOC_SIMPLE_MAX_PO2 2048
#define CONFIG_PMALLOC_SIMPLE_MAX_PO3 2048
#define CONFIG_PMALLOC_SIMPLE_MAX_PO4 512
#define CONFIG_PMALLOC_SIMPLE_MAX_PO5 512
#define CONFIG_PMALLOC_SIMPLE_MAX_PO6 128
#define CONFIG_PMALLOC_SIMPLE_MAX_PO7 128
#define CONFIG_PMALLOC_SIMPLE_MAX_PO8 64
#define CONFIG_PMALLOC_SIMPLE_MAX_PO9 32