#ifndef __LUNAIX_CONFIG_H
#define __LUNAIX_CONFIG_H

// #define CONFIG_PMALLOC_BUDDY
// #define CONFIG_PMALLOC_NCONTIG
#define CONFIG_PMALLOC_SIMPLE

#define CONFIG_PMALLOC_SIMPLE_PO0_THRES     4096
#define CONFIG_PMALLOC_SIMPLE_PO1_THRES     2048
#define CONFIG_PMALLOC_SIMPLE_PO2_THRES     2048
#define CONFIG_PMALLOC_SIMPLE_PO3_THRES     2048
#define CONFIG_PMALLOC_SIMPLE_PO4_THRES     512
#define CONFIG_PMALLOC_SIMPLE_PO5_THRES     512
#define CONFIG_PMALLOC_SIMPLE_PO6_THRES     128
#define CONFIG_PMALLOC_SIMPLE_PO7_THRES     128
#define CONFIG_PMALLOC_SIMPLE_PO8_THRES     64
#define CONFIG_PMALLOC_SIMPLE_PO9_THRES     16

#endif /* __LUNAIX_CONFIG_H */
