include config/make-locations
include config/make-os
include config/make-cc

SRC_FILES := $(wildcard uprog/*.c)
PROGRAMES := $(patsubst uprog/%.c, $(USR_DIR)/%, $(SRC_FILES))

$(USR_DIR)/%:
	@echo "  BUILD   $(*F)"
	@$(CC) -T usr/link-usr.ld $(INCLUDES) $(CFLAGS) -g $(LDFLAGS) uprog/$(*F).c $(BIN_DIR)/$(USR_LIB) -o $@

all: $(PROGRAMES)