#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

sym_types=$1
bin=$2

nm_out=$(nm -nfbsd "$bin")
class_info=$($SCRIPT_DIR/elftool.tool -t -i $bin)

allsyms=($nm_out)
allsyms_len=${#allsyms[@]}

dtype="4byte"
if [ "$class_info" == 'ELF64' ]; then
    dtype="8byte"
fi

syms_idx=()

for (( i=0; i<allsyms_len; i+=3));
do
    type=${allsyms[$i + 1]}

    if [[ "$sym_types" == *"$type"* ]]; then
        syms_idx+=($i)
    fi
done

syms_len=${#syms_idx[@]}
declare -A assoc_array

echo '.section .autogen.ksymtable, "a", @progbits'
echo "    .global __lunaix_ksymtable"
echo "    __lunaix_ksymtable:"
echo "        .$dtype $syms_len"
echo "        .align 8"

for i in "${syms_idx[@]}"
do
    addr=${allsyms[$i]}
    type=${allsyms[$i + 1]}
    sym=${allsyms[$i + 2]}

    cat <<EOF
        .$dtype 0x$addr
        .$dtype __S$sym
        .align 8

EOF
    assoc_array["$sym"]=1
done

for sym_str in "${!assoc_array[@]}"
do
    cat <<EOF
    __S$sym_str:
        .asciz "$sym_str"
        .align 8
EOF
done